# Web site staging services:
staging:
  profile: ~
  whoami: master

jekyll:
  whoami: master
  target: asf-site

publish:
  whoami: asf-site
  hostname: www.eventmesher.com

notifications:
  commits: commits@eventmesh.apache.org
  issues: commits@eventmesh.apache.org
  pullrequests_status: commits@eventmesh.apache.org
  pullrequests_comment: commits@eventmesh.apache.org
  issues_status: dev@eventmesh.apache.org
  issues_comment: commits@eventmesh.apache.org
  jira_options: link label worklog
